name: Write Syllabus to PDF

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Markdown to PDF and HTML
      uses: BaileyJM02/markdown-to-pdf@v1.2.0
      with:
        input_path: syllabus
        output_dir: syllabus

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: syllabus
        path: syllabus/*.pdf
